# Generated by Django 2.1.3 on 2018-11-22 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=10, unique=True)),
                ('grade', models.CharField(max_length=4)),
                ('exam_update', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('subjects', models.IntegerField(default=0)),
                ('classnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doofen.Classnum')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.IntegerField()),
                ('content', models.TextField()),
                ('add_date', models.DateField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doofen.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('last_update', models.DateField()),
                ('classnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doofen.Classnum')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doofen.Student'),
        ),
    ]
