# Generated by Django 2.1.3 on 2018-11-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doofen', '0002_auto_20181122_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnum',
            name='class_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
