# Generated by Django 2.1.3 on 2018-11-24 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doofen', '0003_auto_20181122_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_use', models.DateTimeField(default=None, null=True)),
                ('content', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='summary_subs',
            field=models.IntegerField(default=0),
        ),
    ]
