# Generated by Django 2.1.3 on 2018-11-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doofen', '0004_auto_20181124_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='content',
            field=models.CharField(max_length=32),
        ),
    ]
