# Generated by Django 2.1.3 on 2018-11-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doofen', '0005_auto_20181124_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passwd_md5',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
