# Generated by Django 2.1.3 on 2018-11-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doofen', '0006_auto_20181126_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passwd_md5',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
