# Generated by Django 2.1.3 on 2018-11-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doofen', '0007_auto_20181126_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passwd_md5',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
