# Generated by Django 2.1.3 on 2018-11-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doofen', '0008_auto_20181126_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(null=True),
        ),
    ]
