# Generated by Django 2.1.3 on 2018-11-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doofen', '0009_exam_exam_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(max_length=11)),
                ('valid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doofen.Student')),
            ],
        ),
    ]
